### ISSUE TITLE
Move $inuit-font-size-hX vars to _settings.core.scss

### ISSUE THREAD

**Issue by inlikealion** [inuitcss/inuitcss#371]
I just landed on an issue while upgrading a legacy code base from the beta to the `6.0.0` release: 

Since #291 the `$inuit-font-size-hX` variables are defined in `_elements.headings.scss` but not in `_utilities.headings.scss`. This means that if you do not include the `_elements.headings.scss` in your project, the `_utilities.headings.scss` throws up ‘Undefined variable: “$inuit-font-size-h1”’ errors. 

I believe these should be defined in `_settings.core.scss` instead to adhere to the principal of being able to turn off (or not include) the various inuitcss modules. 

I've been out of the inuitcss activity the past 1+ years, so I recognize I may be misinformed. Thanks for pushing this project forward, Team!

**Comment by inlikealion** [comment]
If moving the definitions to `_settings.core.scss` is the correct move forward, I'll happily work on a pull-request.

**Comment by herzinger** [comment]
That's a bit delicate. You are 100% right that `_elements.headings.scss` is not the right place for that, but neither is `_settings.core.scss`. I'll break it down:

I don't think variables should be set in any layer other than settings or - in some cases - tools. Part of that is semantics, and there would be no problem if said variables were to be used on that particular file only. But otherwise it will introduce the type of problem you speak of. That being said, setting it in `settings.core.scss` breaks modularity (as if you do not import the headings related modules, you end up with some useless, unused variables left) and introduces some highly configurable and opitionated variables to a file that, by design, shouldn't really be touched by the user.

The most appropriate place for that kind of setup, to my view, is `settings.globals.scss`(that's where I set this type of stuff in my own projects), but the way it is right now, it's presented as an exemple file. That is also a side-effect and signal that the whole headings setup is uncharacteristically opitionated for this project standards, but well, this is a common enough pattern. There are two approaches I see to solve this: 

1. To make both `_elements.headings.scss` and `_utilities.headings.scss`exemple files, which would drive home even more the generic, design agnostic nature of the framework while still maintaining a solid usage reference; or
2. To make `settings.globals.scss` an official part of the framework, documented as a first place to start to personalize the settings for each specific project.

I'd be happy with either, and both would solve this issue.

**Comment by LayZeeDK** [comment]
Option 3: Add `_settings.headings.scss`.
Option 4: Add headings variables to `_utilities.headings.scss` with the `!default` flag.

**Comment by florianbouvot** [comment]
I'm in favor of moving headings variables to `_settings.globals.scss` or `_settings.headings.scss`.

**Comment by herzinger** [comment]
> Option 3: Add `_settings.headings.scss`.

This is acceptable as well, yes.

> Option 4: Add headings variables to `_utilities.headings.scss` with the `!default` flag.

This has the same problems as leaving where it is now: if you don't want the utilities you'll see the same error, but now in the elements layer, and the semantics stay wrong.

**Comment by LayZeeDK** [comment]
> > Option 4: Add headings variables to `_utilities.headings.scss` with the `!default` flag.
> 
> This has the same problems as leaving where it is now: if you don't want the utilities you'll see the same error, but now in the elements layer, and the semantics stay wrong.

By option 4, I mean this

```
// _elements.headings.scss
/* ==========================================================================
   #HEADINGS
   ========================================================================== */

$inuit-font-size-h1:  36px !default;
$inuit-font-size-h2:  28px !default;
$inuit-font-size-h3:  24px !default;
$inuit-font-size-h4:  20px !default;
$inuit-font-size-h5:  18px !default;
$inuit-font-size-h6:  16px !default;

h1 {
  @include inuit-font-size($inuit-font-size-h1);
}

// Etc.
```

```
// _utilities.headings.scss
/* ==========================================================================
   #HEADINGS
   ========================================================================== */

$inuit-font-size-h1:  36px !default;
$inuit-font-size-h2:  28px !default;
$inuit-font-size-h3:  24px !default;
$inuit-font-size-h4:  20px !default;
$inuit-font-size-h5:  18px !default;
$inuit-font-size-h6:  16px !default;

.u-h1 {
  @include inuit-font-size($inuit-font-size-h1, $important: true);
}

// Etc.
```

This way they will work independently of each other.

**Comment by herzinger** [comment]
hell no.

**Comment by jools-r** [comment]
> hell no.

Would you care to explain why (an honest question)?

As I see it (which could be short-sighted I readily admit) LayZeeDK's approach:
- maintains the independent usability of the different imports
- solves the problem of imports being interdependent (the original problem)
- respects settings made in a central settings file (whether in an own settings file or combined settings file)
- doesn't introduce new files (like a separate settings file)
- doesn't introduce new steps to using inuitcss (like having to rename example files, which people are likely to forget because "example" doesn't suggest that it is a necessary file)

Why I ask: I often use this approach with variables in my own components so that they are portable between projects and function on their own without causing compilation errors because I've forgotten to set a central variable in the settings. Where possible/sensible, I try and tie those variables back to some central variable (like a spacing variable) for consistency's sake but that's not always appropriate. Is that not good practice?

**Comment by herzinger** [comment]
> Would you care to explain why (an honest question)?

Yes, sorry. It does solve the issue at hand, that's not the problem. It's just that this much code duplication is hacky, ugly and unnecessary, specially when there are better solutions on the table.

> [it] maintains the independent usability of the different imports
> [it] solves the problem of imports being interdependent (the original problem)

That it does, by duplicating the declarations. I'm aware variable declarations don't make it into the final transpiled file, but it IS used in said transpilation, has to be maintained "in sync", and is - I'll admit, more importantly for me - an ugly as fuck pattern. 

> [it] respects settings made in a central settings file (whether in an own settings file or combined settings file)

It doesn't. Neither one of the repeated block of variables is in the settings (or tools) layer. It's doubling down on the mistake instead of fixing it. Obviously, you can overwrite all the variables in a central place thanks to the `!default` flag, but why not to that right from the start?

> [it] doesn't introduce new files (like a separate settings file)

That isn't an issue anyway.

> [it] doesn't introduce new steps to using inuitcss (like having to rename example files, which people are likely to forget because "example" doesn't suggest that it is a necessary file)

Exemple files are not meant to be a mandatory step of the framework's setup, just a reference. That's why I said we should either make the whole headings stuff example files, or make the `_settings.global.scss` NOT an example, but an official part of the framework, one that would centralize the more optionated settings we provide out of the box. If I had to cast a vote, that last one option would be it, as I find it the most elegant and still in touch with this project's philosophy. The `_settings.headings.scss` approach is still quite acceptable, and the double declarations is an abomination, in my opinion, and I refuse to endorse it hahaha

> Is that not good practice?

This is of course open to interpretation, like most "best practices" advices, but I'm personally a huge fan of semantics, and as I said before, I believe settings variables should always go in the settings layer, with in some cases exception for tools related variables that are used in that file only (those going in the tools layer, obviously), and even then generally default parameter values are a better option. As a rule of thumb, I don't set variables in component (or object, or utilities, etc...) files.

In short: hell to the no o/"

**Comment by jools-r** [comment]
Thanks for the eloquent answer, both the objective and the opinionated parts ;-)

You'll decide, I guess, which is preferable. If you switch to centralised heading variables, it might be helpful to add a corresponding note in the elements and utilities files that the variables are defined in the _settings.whatever.scss file. Just easier for noobs to find answers to potential errors on their own.

**Comment by LayZeeDK** [comment]
I agree that separating the variable definitions from the elements and utilities is more in line with the philosophy of inutcss and ITCSS. This easy-to-grog concern is a good candidate to express best practice of separating reusable variables into the settings layer.

There is certainly an educational issue that needs to be addressed. Including `_settings.headings.scss` and the corresponding elements and utilities in `example.main.scss` is a good starting point.

**Comment by herzinger** [comment]
> You'll decide, I guess, which is preferable. 

I'm not even the one to decide, I'm just pretentious ;)"

**Comment by florianbouvot** [comment]
@herzinger I vote for `_settings.global.scss` with headings settings and may be more. In v6.1 or directly in v7 ?

**Comment by herzinger** [comment]
v7, imo

**Comment by csshugs** [comment]
We will leave this topic untouched for v6 and instead decide how we want to handle this for v7 in #390.
